export const GET_ALL_REPORT_USERS_REQUEST = "GET_ALL_REPORT_USERS_REQUEST";
export const GET_ALL_REPORT_USERS_SUCCESS = "GET_ALL_REPORT_USERS_SUCCESS";
export const GET_ALL_REPORT_USERS_ERROR = "GET_ALL_REPORT_USERS_ERROR";

export const GET_DETAIL_REPORT_USERS_REQUEST = "GET_DETAIL_REPORT_USERS_REQUEST";
export const GET_DETAIL_REPORT_USERS_SUCCESS = "GET_DETAIL_REPORT_USERS_SUCCESS";
export const GET_DETAIL_REPORT_USERS_ERROR = "GET_DETAIL_REPORT_USERS_ERROR";

export const UPDATE_ALPHABET_DETAILS_REQUEST = "UPDATE_ALPHABET_DETAILS_REQUEST";
export const UPDATE_ALPHABET_DETAILS_SUCCESS = "UPDATE_ALPHABET_DETAILS_SUCCESS";
export const UPDATE_ALPHABET_DETAILS_ERROR = "UPDATE_ALPHABET_DETAILS_ERROR";

export const DELETE_ALPHABET_DETAILS_REQUEST = "DELETE_ALPHABET_DETAILS_REQUEST";
export const DELETE_ALPHABET_DETAILS_SUCCESS = "DELETE_ALPHABET_DETAILS_SUCCESS";
export const DELETE_ALPHABET_DETAILS_ERROR = "DELETE_ALPHABET_DETAILS_ERROR"

// export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
// export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST"
// export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR"

// export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
// export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST"
// export const POST_COMMENT_ERROR = "POST_COMMENT_ERROR"
